package com.cs.lexiao.admin.mapping.business;

/**
 * FiCodeKey generated by hbm2java
 */
public class FiCodeKey {

	private String codeKey;
	private String keyName;
	private String langType;

	public FiCodeKey() {
	}

	public String getCodeKey() {
		return codeKey;
	}

	public void setCodeKey(String codeKey) {
		this.codeKey = codeKey;
	}

	public String getKeyName() {
		return keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	public String getLangType() {
		return langType;
	}

	public void setLangType(String langType) {
		this.langType = langType;
	}

}
