package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxAudit generated by hbm2java
 */
@Entity
@Table(name="lx_audit"
    ,catalog="lexiao"
)
public class LxAudit  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private byte type;
     private int referenceId;
     private byte status;
     private String remark;
     private String rejectReason;
     private int mtime;
     private int ctime;

    public LxAudit() {
    }

	
    public LxAudit(int uid, byte type, int referenceId, byte status, int mtime, int ctime) {
        this.uid = uid;
        this.type = type;
        this.referenceId = referenceId;
        this.status = status;
        this.mtime = mtime;
        this.ctime = ctime;
    }
    public LxAudit(int uid, byte type, int referenceId, byte status, String remark, String rejectReason, int mtime, int ctime) {
       this.uid = uid;
       this.type = type;
       this.referenceId = referenceId;
       this.status = status;
       this.remark = remark;
       this.rejectReason = rejectReason;
       this.mtime = mtime;
       this.ctime = ctime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="reference_id", nullable=false)
    public int getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(int referenceId) {
        this.referenceId = referenceId;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="remark", length=256)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="reject_reason", length=256)
    public String getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    
    @Column(name="mtime", nullable=false)
    public int getMtime() {
        return this.mtime;
    }
    
    public void setMtime(int mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }




}


