package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxBanner generated by hbm2java
 */
@Entity
@Table(name="lx_banner"
    ,catalog="lexiao"
)
public class LxBanner  implements java.io.Serializable {


     private Integer id;
     private String title;
     private Integer position;
     private String img;
     private Integer sort;
     private String href;
     private Integer ctime;
     private Integer mtime;
     private Boolean isActive;
     private String content;
     private String miNo;
     private Integer starttime;
     private Integer endtime;

    public LxBanner() {
    }

    public LxBanner(String title, Integer position, String img, Integer sort, String href, Integer ctime, Integer mtime, Boolean isActive, String content, String miNo, Integer starttime, Integer endtime) {
       this.title = title;
       this.position = position;
       this.img = img;
       this.sort = sort;
       this.href = href;
       this.ctime = ctime;
       this.mtime = mtime;
       this.isActive = isActive;
       this.content = content;
       this.miNo = miNo;
       this.starttime = starttime;
       this.endtime = endtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="img", length=100)
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

    
    @Column(name="sort")
    public Integer getSort() {
        return this.sort;
    }
    
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    
    @Column(name="href", length=100)
    public String getHref() {
        return this.href;
    }
    
    public void setHref(String href) {
        this.href = href;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="mi_no", length=20)
    public String getMiNo() {
        return this.miNo;
    }
    
    public void setMiNo(String miNo) {
        this.miNo = miNo;
    }

    
    @Column(name="starttime")
    public Integer getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Integer starttime) {
        this.starttime = starttime;
    }

    
    @Column(name="endtime")
    public Integer getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Integer endtime) {
        this.endtime = endtime;
    }




}


