package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxBdBonusRecord generated by hbm2java
 */
@Entity
@Table(name="lx_bd_bonus_record"
    ,catalog="lexiao"
)
public class LxBdBonusRecord  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private int bdId;
     private byte bonusType;
     private BigDecimal amount;
     private byte isDel;
     private int mtime;
     private int ctime;

    public LxBdBonusRecord() {
    }

	
    public LxBdBonusRecord(int uid, int bdId, byte bonusType, byte isDel, int mtime, int ctime) {
        this.uid = uid;
        this.bdId = bdId;
        this.bonusType = bonusType;
        this.isDel = isDel;
        this.mtime = mtime;
        this.ctime = ctime;
    }
    public LxBdBonusRecord(int uid, int bdId, byte bonusType, BigDecimal amount, byte isDel, int mtime, int ctime) {
       this.uid = uid;
       this.bdId = bdId;
       this.bonusType = bonusType;
       this.amount = amount;
       this.isDel = isDel;
       this.mtime = mtime;
       this.ctime = ctime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

    
    @Column(name="bd_id", nullable=false)
    public int getBdId() {
        return this.bdId;
    }
    
    public void setBdId(int bdId) {
        this.bdId = bdId;
    }

    
    @Column(name="bonus_type", nullable=false)
    public byte getBonusType() {
        return this.bonusType;
    }
    
    public void setBonusType(byte bonusType) {
        this.bonusType = bonusType;
    }

    
    @Column(name="amount", precision=20)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="is_del", nullable=false)
    public byte getIsDel() {
        return this.isDel;
    }
    
    public void setIsDel(byte isDel) {
        this.isDel = isDel;
    }

    
    @Column(name="mtime", nullable=false)
    public int getMtime() {
        return this.mtime;
    }
    
    public void setMtime(int mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }




}


