package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LxCashoutApply generated by hbm2java
 */
@Entity
@Table(name="lx_cashout_apply"
    ,catalog="lexiao"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cashout_no"), @UniqueConstraint(columnNames="trans_no")} 
)
public class LxCashoutApply  implements java.io.Serializable {


     private Integer id;
     private Integer ctime;
     private Integer mtime;
     private String cashoutNo;
     private Integer outUid;
     private Integer cashUid;
     private Integer applyAmount;
     private Integer actualAmount;
     private Integer feeRate;
     private Integer fee;
     private Integer actualDate;
     private Byte days;
     private String bankCode;
     private String bankName;
     private String accountNo;
     private String accountName;
     private String channel;
     private String transNo;
     private String transRet;
     private Byte status;
     private Integer auditor;
     private Integer auditTime;
     private Boolean auditStatus;
     private String auditRemark;
     private String remark;

    public LxCashoutApply() {
    }

    public LxCashoutApply(Integer ctime, Integer mtime, String cashoutNo, Integer outUid, Integer cashUid, Integer applyAmount, Integer actualAmount, Integer feeRate, Integer fee, Integer actualDate, Byte days, String bankCode, String bankName, String accountNo, String accountName, String channel, String transNo, String transRet, Byte status, Integer auditor, Integer auditTime, Boolean auditStatus, String auditRemark, String remark) {
       this.ctime = ctime;
       this.mtime = mtime;
       this.cashoutNo = cashoutNo;
       this.outUid = outUid;
       this.cashUid = cashUid;
       this.applyAmount = applyAmount;
       this.actualAmount = actualAmount;
       this.feeRate = feeRate;
       this.fee = fee;
       this.actualDate = actualDate;
       this.days = days;
       this.bankCode = bankCode;
       this.bankName = bankName;
       this.accountNo = accountNo;
       this.accountName = accountName;
       this.channel = channel;
       this.transNo = transNo;
       this.transRet = transRet;
       this.status = status;
       this.auditor = auditor;
       this.auditTime = auditTime;
       this.auditStatus = auditStatus;
       this.auditRemark = auditRemark;
       this.remark = remark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="cashout_no", unique=true, length=30)
    public String getCashoutNo() {
        return this.cashoutNo;
    }
    
    public void setCashoutNo(String cashoutNo) {
        this.cashoutNo = cashoutNo;
    }

    
    @Column(name="out_uid")
    public Integer getOutUid() {
        return this.outUid;
    }
    
    public void setOutUid(Integer outUid) {
        this.outUid = outUid;
    }

    
    @Column(name="cash_uid")
    public Integer getCashUid() {
        return this.cashUid;
    }
    
    public void setCashUid(Integer cashUid) {
        this.cashUid = cashUid;
    }

    
    @Column(name="apply_amount")
    public Integer getApplyAmount() {
        return this.applyAmount;
    }
    
    public void setApplyAmount(Integer applyAmount) {
        this.applyAmount = applyAmount;
    }

    
    @Column(name="actual_amount")
    public Integer getActualAmount() {
        return this.actualAmount;
    }
    
    public void setActualAmount(Integer actualAmount) {
        this.actualAmount = actualAmount;
    }

    
    @Column(name="fee_rate")
    public Integer getFeeRate() {
        return this.feeRate;
    }
    
    public void setFeeRate(Integer feeRate) {
        this.feeRate = feeRate;
    }

    
    @Column(name="fee")
    public Integer getFee() {
        return this.fee;
    }
    
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    
    @Column(name="actual_date")
    public Integer getActualDate() {
        return this.actualDate;
    }
    
    public void setActualDate(Integer actualDate) {
        this.actualDate = actualDate;
    }

    
    @Column(name="days")
    public Byte getDays() {
        return this.days;
    }
    
    public void setDays(Byte days) {
        this.days = days;
    }

    
    @Column(name="bank_code", length=10)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="bank_name", length=50)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="account_no", length=30)
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    
    @Column(name="account_name", length=30)
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    
    @Column(name="channel", length=10)
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }

    
    @Column(name="trans_no", unique=true, length=30)
    public String getTransNo() {
        return this.transNo;
    }
    
    public void setTransNo(String transNo) {
        this.transNo = transNo;
    }

    
    @Column(name="trans_ret", length=200)
    public String getTransRet() {
        return this.transRet;
    }
    
    public void setTransRet(String transRet) {
        this.transRet = transRet;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

    
    @Column(name="auditor")
    public Integer getAuditor() {
        return this.auditor;
    }
    
    public void setAuditor(Integer auditor) {
        this.auditor = auditor;
    }

    
    @Column(name="audit_time")
    public Integer getAuditTime() {
        return this.auditTime;
    }
    
    public void setAuditTime(Integer auditTime) {
        this.auditTime = auditTime;
    }

    
    @Column(name="audit_status")
    public Boolean getAuditStatus() {
        return this.auditStatus;
    }
    
    public void setAuditStatus(Boolean auditStatus) {
        this.auditStatus = auditStatus;
    }

    
    @Column(name="audit_remark", length=100)
    public String getAuditRemark() {
        return this.auditRemark;
    }
    
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark;
    }

    
    @Column(name="remark", length=1000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


