package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxCodeItem generated by hbm2java
 */
@Entity
@Table(name="lx_code_item"
    ,catalog="lexiao"
)
public class LxCodeItem  implements java.io.Serializable {


     private Integer id;
     private String codeKey;
     private String codeNo;
     private String codeName;
     private String langType;
     private int order;
     private boolean isPublic;

    public LxCodeItem() {
    }

	
    public LxCodeItem(int order, boolean isPublic) {
        this.order = order;
        this.isPublic = isPublic;
    }
    public LxCodeItem(String codeKey, String codeNo, String codeName, String langType, int order, boolean isPublic) {
       this.codeKey = codeKey;
       this.codeNo = codeNo;
       this.codeName = codeName;
       this.langType = langType;
       this.order = order;
       this.isPublic = isPublic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code_key", length=10)
    public String getCodeKey() {
        return this.codeKey;
    }
    
    public void setCodeKey(String codeKey) {
        this.codeKey = codeKey;
    }

    
    @Column(name="code_no", length=30)
    public String getCodeNo() {
        return this.codeNo;
    }
    
    public void setCodeNo(String codeNo) {
        this.codeNo = codeNo;
    }

    
    @Column(name="code_name", length=100)
    public String getCodeName() {
        return this.codeName;
    }
    
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    
    @Column(name="lang_type", length=10)
    public String getLangType() {
        return this.langType;
    }
    
    public void setLangType(String langType) {
        this.langType = langType;
    }

    
    @Column(name="order", nullable=false)
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }

    
    @Column(name="is_public", nullable=false)
    public boolean isIsPublic() {
        return this.isPublic;
    }
    
    public void setIsPublic(boolean isPublic) {
        this.isPublic = isPublic;
    }




}


