package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxConfig generated by hbm2java
 */
@Entity
@Table(name="lx_config"
    ,catalog="lexiao"
)
public class LxConfig  implements java.io.Serializable {


     private Integer id;
     private byte type;
     private Integer platId;
     private byte status;
     private String content;
     private int mtime;
     private int ctime;

    public LxConfig() {
    }

	
    public LxConfig(byte type, byte status, int mtime, int ctime) {
        this.type = type;
        this.status = status;
        this.mtime = mtime;
        this.ctime = ctime;
    }
    public LxConfig(byte type, Integer platId, byte status, String content, int mtime, int ctime) {
       this.type = type;
       this.platId = platId;
       this.status = status;
       this.content = content;
       this.mtime = mtime;
       this.ctime = ctime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="content", length=256)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="mtime", nullable=false)
    public int getMtime() {
        return this.mtime;
    }
    
    public void setMtime(int mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }




}


