package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LxCodeKey generated by hbm2java
 */
@Entity
@Table(name="lx_code_key"
    ,catalog="lexiao"
    , uniqueConstraints = @UniqueConstraint(columnNames="code_key") 
)
public class LxCodeKey  implements java.io.Serializable {


     private LxCodeKeyId id;

    public LxCodeKey() {
    }

    public LxCodeKey(LxCodeKeyId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codeKey", column=@Column(name="code_key", unique=true, length=10) ), 
        @AttributeOverride(name="keyName", column=@Column(name="key_name", length=100) ), 
        @AttributeOverride(name="langType", column=@Column(name="lang_type", length=10) ), 
        @AttributeOverride(name="isNew", column=@Column(name="is_new", nullable=false) ) } )
    public LxCodeKeyId getId() {
        return this.id;
    }
    
    public void setId(LxCodeKeyId id) {
        this.id = id;
    }




}


