package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LxCouponTemplate generated by hbm2java
 */
@Entity
@Table(name="lx_coupon_template"
    ,catalog="lexiao"
)
public class LxCouponTemplate  implements java.io.Serializable {


     private Integer id;
     private byte type;
     private boolean status;
     private BigDecimal discountAmount;
     private BigDecimal needAmount;
     private int publishNum;
     private int receivedNum;
     private int usedNum;
     private byte scope;
     private String needWeek;
     private Date needTimeStart;
     private Date needTimeEnd;
     private int offTime;
     private boolean isFree;
     private String useRule;
     private int createUserId;
     private Integer authUserId;
     private Integer authTime;
     private String rejectReason;
     private int ctime;
     private Integer mtime;

    public LxCouponTemplate() {
    }

	
    public LxCouponTemplate(byte type, boolean status, BigDecimal discountAmount, int publishNum, int receivedNum, int usedNum, byte scope, String needWeek, Date needTimeStart, Date needTimeEnd, int offTime, boolean isFree, String useRule, int createUserId, int ctime) {
        this.type = type;
        this.status = status;
        this.discountAmount = discountAmount;
        this.publishNum = publishNum;
        this.receivedNum = receivedNum;
        this.usedNum = usedNum;
        this.scope = scope;
        this.needWeek = needWeek;
        this.needTimeStart = needTimeStart;
        this.needTimeEnd = needTimeEnd;
        this.offTime = offTime;
        this.isFree = isFree;
        this.useRule = useRule;
        this.createUserId = createUserId;
        this.ctime = ctime;
    }
    public LxCouponTemplate(byte type, boolean status, BigDecimal discountAmount, BigDecimal needAmount, int publishNum, int receivedNum, int usedNum, byte scope, String needWeek, Date needTimeStart, Date needTimeEnd, int offTime, boolean isFree, String useRule, int createUserId, Integer authUserId, Integer authTime, String rejectReason, int ctime, Integer mtime) {
       this.type = type;
       this.status = status;
       this.discountAmount = discountAmount;
       this.needAmount = needAmount;
       this.publishNum = publishNum;
       this.receivedNum = receivedNum;
       this.usedNum = usedNum;
       this.scope = scope;
       this.needWeek = needWeek;
       this.needTimeStart = needTimeStart;
       this.needTimeEnd = needTimeEnd;
       this.offTime = offTime;
       this.isFree = isFree;
       this.useRule = useRule;
       this.createUserId = createUserId;
       this.authUserId = authUserId;
       this.authTime = authTime;
       this.rejectReason = rejectReason;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="discount_amount", nullable=false, precision=20, scale=0)
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }
    
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    
    @Column(name="need_amount", precision=20, scale=0)
    public BigDecimal getNeedAmount() {
        return this.needAmount;
    }
    
    public void setNeedAmount(BigDecimal needAmount) {
        this.needAmount = needAmount;
    }

    
    @Column(name="publish_num", nullable=false)
    public int getPublishNum() {
        return this.publishNum;
    }
    
    public void setPublishNum(int publishNum) {
        this.publishNum = publishNum;
    }

    
    @Column(name="received_num", nullable=false)
    public int getReceivedNum() {
        return this.receivedNum;
    }
    
    public void setReceivedNum(int receivedNum) {
        this.receivedNum = receivedNum;
    }

    
    @Column(name="used_num", nullable=false)
    public int getUsedNum() {
        return this.usedNum;
    }
    
    public void setUsedNum(int usedNum) {
        this.usedNum = usedNum;
    }

    
    @Column(name="scope", nullable=false)
    public byte getScope() {
        return this.scope;
    }
    
    public void setScope(byte scope) {
        this.scope = scope;
    }

    
    @Column(name="need_week", nullable=false)
    public String getNeedWeek() {
        return this.needWeek;
    }
    
    public void setNeedWeek(String needWeek) {
        this.needWeek = needWeek;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="need_time_start", nullable=false, length=8)
    public Date getNeedTimeStart() {
        return this.needTimeStart;
    }
    
    public void setNeedTimeStart(Date needTimeStart) {
        this.needTimeStart = needTimeStart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="need_time_end", nullable=false, length=8)
    public Date getNeedTimeEnd() {
        return this.needTimeEnd;
    }
    
    public void setNeedTimeEnd(Date needTimeEnd) {
        this.needTimeEnd = needTimeEnd;
    }

    
    @Column(name="off_time", nullable=false)
    public int getOffTime() {
        return this.offTime;
    }
    
    public void setOffTime(int offTime) {
        this.offTime = offTime;
    }

    
    @Column(name="is_free", nullable=false)
    public boolean isIsFree() {
        return this.isFree;
    }
    
    public void setIsFree(boolean isFree) {
        this.isFree = isFree;
    }

    
    @Column(name="use_rule", nullable=false, length=65535)
    public String getUseRule() {
        return this.useRule;
    }
    
    public void setUseRule(String useRule) {
        this.useRule = useRule;
    }

    
    @Column(name="create_user_id", nullable=false)
    public int getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(int createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="auth_user_id")
    public Integer getAuthUserId() {
        return this.authUserId;
    }
    
    public void setAuthUserId(Integer authUserId) {
        this.authUserId = authUserId;
    }

    
    @Column(name="auth_time")
    public Integer getAuthTime() {
        return this.authTime;
    }
    
    public void setAuthTime(Integer authTime) {
        this.authTime = authTime;
    }

    
    @Column(name="reject_reason", length=1000)
    public String getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


