package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxCouponTemplateMerchant generated by hbm2java
 */
@Entity
@Table(name="lx_coupon_template_merchant"
    ,catalog="lexiao"
)
public class LxCouponTemplateMerchant  implements java.io.Serializable {


     private Integer id;
     private int couponTemplateId;
     private byte isMain;
     private int MId;
     private int ctime;
     private Integer mtime;

    public LxCouponTemplateMerchant() {
    }

	
    public LxCouponTemplateMerchant(int couponTemplateId, byte isMain, int MId, int ctime) {
        this.couponTemplateId = couponTemplateId;
        this.isMain = isMain;
        this.MId = MId;
        this.ctime = ctime;
    }
    public LxCouponTemplateMerchant(int couponTemplateId, byte isMain, int MId, int ctime, Integer mtime) {
       this.couponTemplateId = couponTemplateId;
       this.isMain = isMain;
       this.MId = MId;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="coupon_template_id", nullable=false)
    public int getCouponTemplateId() {
        return this.couponTemplateId;
    }
    
    public void setCouponTemplateId(int couponTemplateId) {
        this.couponTemplateId = couponTemplateId;
    }

    
    @Column(name="is_main", nullable=false)
    public byte getIsMain() {
        return this.isMain;
    }
    
    public void setIsMain(byte isMain) {
        this.isMain = isMain;
    }

    
    @Column(name="m_id", nullable=false)
    public int getMId() {
        return this.MId;
    }
    
    public void setMId(int MId) {
        this.MId = MId;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


