package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxMerchantImg generated by hbm2java
 */
@Entity
@Table(name="lx_merchant_img"
    ,catalog="lexiao"
)
public class LxMerchantImg  implements java.io.Serializable {


     private Integer id;
     private int MId;
     private int imgId;
     private byte type;
     private byte status;
     private Integer ctime;
     private Integer mtime;
     private Integer creator;
     private Integer modifier;

    public LxMerchantImg() {
    }

	
    public LxMerchantImg(int MId, int imgId, byte type, byte status) {
        this.MId = MId;
        this.imgId = imgId;
        this.type = type;
        this.status = status;
    }
    public LxMerchantImg(int MId, int imgId, byte type, byte status, Integer ctime, Integer mtime, Integer creator, Integer modifier) {
       this.MId = MId;
       this.imgId = imgId;
       this.type = type;
       this.status = status;
       this.ctime = ctime;
       this.mtime = mtime;
       this.creator = creator;
       this.modifier = modifier;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="m_id", nullable=false)
    public int getMId() {
        return this.MId;
    }
    
    public void setMId(int MId) {
        this.MId = MId;
    }

    
    @Column(name="img_id", nullable=false)
    public int getImgId() {
        return this.imgId;
    }
    
    public void setImgId(int imgId) {
        this.imgId = imgId;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="creator")
    public Integer getCreator() {
        return this.creator;
    }
    
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    
    @Column(name="modifier")
    public Integer getModifier() {
        return this.modifier;
    }
    
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }




}


