package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxMerchantEmployee generated by hbm2java
 */
@Entity
@Table(name="lx_merchant_employee"
    ,catalog="lexiao"
)
public class LxMerchantEmployee  implements java.io.Serializable {


     private Integer id;
     private Integer mid;
     private Integer uid;
     private String post;
     private String name;
     private String mobile;
     private Byte status;
     private Integer ctime;
     private Integer mtime;
     private Integer creator;
     private Integer modifier;

    public LxMerchantEmployee() {
    }

    public LxMerchantEmployee(Integer mid, Integer uid, String post, String name, String mobile, Byte status, Integer ctime, Integer mtime, Integer creator, Integer modifier) {
       this.mid = mid;
       this.uid = uid;
       this.post = post;
       this.name = name;
       this.mobile = mobile;
       this.status = status;
       this.ctime = ctime;
       this.mtime = mtime;
       this.creator = creator;
       this.modifier = modifier;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="mid")
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="post", length=30)
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mobile", length=30)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="creator")
    public Integer getCreator() {
        return this.creator;
    }
    
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    
    @Column(name="modifier")
    public Integer getModifier() {
        return this.modifier;
    }
    
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }




}


