package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxMerchantInvitation generated by hbm2java
 */
@Entity
@Table(name="lx_merchant_invitation"
    ,catalog="lexiao"
)
public class LxMerchantInvitation  implements java.io.Serializable {


     private Integer id;
     private Integer uid;
     private Integer mid;
     private BigDecimal firstInvest;
     private BigDecimal reward;
     private Byte rewardType;
     private Integer platId;
     private Integer ctime;

    public LxMerchantInvitation() {
    }

    public LxMerchantInvitation(Integer uid, Integer mid, BigDecimal firstInvest, BigDecimal reward, Byte rewardType, Integer platId, Integer ctime) {
       this.uid = uid;
       this.mid = mid;
       this.firstInvest = firstInvest;
       this.reward = reward;
       this.rewardType = rewardType;
       this.platId = platId;
       this.ctime = ctime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="mid")
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    
    @Column(name="first_invest", precision=20, scale=0)
    public BigDecimal getFirstInvest() {
        return this.firstInvest;
    }
    
    public void setFirstInvest(BigDecimal firstInvest) {
        this.firstInvest = firstInvest;
    }

    
    @Column(name="reward", precision=20, scale=0)
    public BigDecimal getReward() {
        return this.reward;
    }
    
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    
    @Column(name="reward_type")
    public Byte getRewardType() {
        return this.rewardType;
    }
    
    public void setRewardType(Byte rewardType) {
        this.rewardType = rewardType;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }




}


