package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxMerchantCategory generated by hbm2java
 */
@Entity
@Table(name="lx_merchant_category"
    ,catalog="lexiao"
)
public class LxMerchantCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String tip;
     private Integer ctime;
     private Integer mtime;
     private Byte isActive;
     private Integer csysid;

    public LxMerchantCategory() {
    }

    public LxMerchantCategory(String name, String tip, Integer ctime, Integer mtime, Byte isActive, Integer csysid) {
       this.name = name;
       this.tip = tip;
       this.ctime = ctime;
       this.mtime = mtime;
       this.isActive = isActive;
       this.csysid = csysid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="tip", length=200)
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="is_active")
    public Byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="csysid")
    public Integer getCsysid() {
        return this.csysid;
    }
    
    public void setCsysid(Integer csysid) {
        this.csysid = csysid;
    }




}


