package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxOutTicket generated by hbm2java
 */
@Entity
@Table(name="lx_out_ticket"
    ,catalog="lexiao"
)
public class LxOutTicket  implements java.io.Serializable {


     private Integer id;
     private int uid;
     private int userOrderId;
     private String tradeNo;
     private int amount;
     private byte status;
     private String channel;
     private String bankNo;
     private Integer accountRecordId;
     private String callBackStr;
     private Boolean inOrOut;
     private int ctime;
     private int mtime;

    public LxOutTicket() {
    }

	
    public LxOutTicket(int uid, int userOrderId, String tradeNo, int amount, byte status, String bankNo, int ctime, int mtime) {
        this.uid = uid;
        this.userOrderId = userOrderId;
        this.tradeNo = tradeNo;
        this.amount = amount;
        this.status = status;
        this.bankNo = bankNo;
        this.ctime = ctime;
        this.mtime = mtime;
    }
    public LxOutTicket(int uid, int userOrderId, String tradeNo, int amount, byte status, String channel, String bankNo, Integer accountRecordId, String callBackStr, Boolean inOrOut, int ctime, int mtime) {
       this.uid = uid;
       this.userOrderId = userOrderId;
       this.tradeNo = tradeNo;
       this.amount = amount;
       this.status = status;
       this.channel = channel;
       this.bankNo = bankNo;
       this.accountRecordId = accountRecordId;
       this.callBackStr = callBackStr;
       this.inOrOut = inOrOut;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }

    
    @Column(name="user_order_id", nullable=false)
    public int getUserOrderId() {
        return this.userOrderId;
    }
    
    public void setUserOrderId(int userOrderId) {
        this.userOrderId = userOrderId;
    }

    
    @Column(name="trade_no", nullable=false, length=30)
    public String getTradeNo() {
        return this.tradeNo;
    }
    
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="channel", length=20)
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }

    
    @Column(name="bank_no", nullable=false, length=30)
    public String getBankNo() {
        return this.bankNo;
    }
    
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    
    @Column(name="account_record_id")
    public Integer getAccountRecordId() {
        return this.accountRecordId;
    }
    
    public void setAccountRecordId(Integer accountRecordId) {
        this.accountRecordId = accountRecordId;
    }

    
    @Column(name="call_back_str", length=200)
    public String getCallBackStr() {
        return this.callBackStr;
    }
    
    public void setCallBackStr(String callBackStr) {
        this.callBackStr = callBackStr;
    }

    
    @Column(name="in_or_out")
    public Boolean getInOrOut() {
        return this.inOrOut;
    }
    
    public void setInOrOut(Boolean inOrOut) {
        this.inOrOut = inOrOut;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime", nullable=false)
    public int getMtime() {
        return this.mtime;
    }
    
    public void setMtime(int mtime) {
        this.mtime = mtime;
    }




}


