package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxPlatformCashConfig generated by hbm2java
 */
@Entity
@Table(name="lx_platform_cash_config"
    ,catalog="lexiao"
)
public class LxPlatformCashConfig  implements java.io.Serializable {


     private Integer id;
     private Integer platId;
     private Integer minCashMoney;
     private Integer cashTip;
     private Integer ctime;
     private Integer mtime;
     private Integer csysid;

    public LxPlatformCashConfig() {
    }

    public LxPlatformCashConfig(Integer platId, Integer minCashMoney, Integer cashTip, Integer ctime, Integer mtime, Integer csysid) {
       this.platId = platId;
       this.minCashMoney = minCashMoney;
       this.cashTip = cashTip;
       this.ctime = ctime;
       this.mtime = mtime;
       this.csysid = csysid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="min_cash_money")
    public Integer getMinCashMoney() {
        return this.minCashMoney;
    }
    
    public void setMinCashMoney(Integer minCashMoney) {
        this.minCashMoney = minCashMoney;
    }

    
    @Column(name="cash_tip")
    public Integer getCashTip() {
        return this.cashTip;
    }
    
    public void setCashTip(Integer cashTip) {
        this.cashTip = cashTip;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="csysid")
    public Integer getCsysid() {
        return this.csysid;
    }
    
    public void setCsysid(Integer csysid) {
        this.csysid = csysid;
    }




}


