package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxPlatfromCoupon generated by hbm2java
 */
@Entity
@Table(name="lx_platfrom_coupon"
    ,catalog="lexiao"
)
public class LxPlatfromCoupon  implements java.io.Serializable {


     private Integer id;
     private Integer platId;
     private byte type;
     private boolean status;
     private BigDecimal discountAmount;
     private String useRule;
     private String callbackUrl;
     private int ctime;
     private Integer mtime;

    public LxPlatfromCoupon() {
    }

	
    public LxPlatfromCoupon(byte type, boolean status, BigDecimal discountAmount, String useRule, int ctime) {
        this.type = type;
        this.status = status;
        this.discountAmount = discountAmount;
        this.useRule = useRule;
        this.ctime = ctime;
    }
    public LxPlatfromCoupon(Integer platId, byte type, boolean status, BigDecimal discountAmount, String useRule, String callbackUrl, int ctime, Integer mtime) {
       this.platId = platId;
       this.type = type;
       this.status = status;
       this.discountAmount = discountAmount;
       this.useRule = useRule;
       this.callbackUrl = callbackUrl;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="discount_amount", nullable=false, precision=20, scale=0)
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }
    
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    
    @Column(name="use_rule", nullable=false, length=65535)
    public String getUseRule() {
        return this.useRule;
    }
    
    public void setUseRule(String useRule) {
        this.useRule = useRule;
    }

    
    @Column(name="callback_url", length=200)
    public String getCallbackUrl() {
        return this.callbackUrl;
    }
    
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    
    @Column(name="ctime", nullable=false)
    public int getCtime() {
        return this.ctime;
    }
    
    public void setCtime(int ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


