package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxPlatformRewardRule generated by hbm2java
 */
@Entity
@Table(name="lx_platform_reward_rule"
    ,catalog="lexiao"
)
public class LxPlatformRewardRule  implements java.io.Serializable {


     private Integer id;
     private Integer platId;
     private BigDecimal minReward;
     private BigDecimal maxReward;
     private BigDecimal ratio;
     private Integer ctime;
     private Integer mtime;

    public LxPlatformRewardRule() {
    }

    public LxPlatformRewardRule(Integer platId, BigDecimal minReward, BigDecimal maxReward, BigDecimal ratio, Integer ctime, Integer mtime) {
       this.platId = platId;
       this.minReward = minReward;
       this.maxReward = maxReward;
       this.ratio = ratio;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="min_reward", precision=20, scale=0)
    public BigDecimal getMinReward() {
        return this.minReward;
    }
    
    public void setMinReward(BigDecimal minReward) {
        this.minReward = minReward;
    }

    
    @Column(name="max_reward", precision=20, scale=0)
    public BigDecimal getMaxReward() {
        return this.maxReward;
    }
    
    public void setMaxReward(BigDecimal maxReward) {
        this.maxReward = maxReward;
    }

    
    @Column(name="ratio", precision=20, scale=0)
    public BigDecimal getRatio() {
        return this.ratio;
    }
    
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


