package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxPlatform generated by hbm2java
 */
@Entity
@Table(name="lx_platform"
    ,catalog="lexiao"
)
public class LxPlatform  implements java.io.Serializable {


     private Integer id;
     private Integer uid;
     private Integer platName;
     private Integer platCode;
     private Integer point;
     private Integer pointVal;
     private Integer welTicketRatio;
     private Integer perShakeCost;
     private Integer shakeRate;
     private BigDecimal regSendMoney;
     private Integer firstInvestWelRatio;
     private BigDecimal firstRegReward;
     private Integer firstInvestRatio;
     private BigDecimal firstInvestReward;
     private Integer status;
     private Integer ctime;
     private Integer mtime;
     private Integer csysid;

    public LxPlatform() {
    }

    public LxPlatform(Integer uid, Integer platName, Integer platCode, Integer point, Integer pointVal, Integer welTicketRatio, Integer perShakeCost, Integer shakeRate, BigDecimal regSendMoney, Integer firstInvestWelRatio, BigDecimal firstRegReward, Integer firstInvestRatio, BigDecimal firstInvestReward, Integer status, Integer ctime, Integer mtime, Integer csysid) {
       this.uid = uid;
       this.platName = platName;
       this.platCode = platCode;
       this.point = point;
       this.pointVal = pointVal;
       this.welTicketRatio = welTicketRatio;
       this.perShakeCost = perShakeCost;
       this.shakeRate = shakeRate;
       this.regSendMoney = regSendMoney;
       this.firstInvestWelRatio = firstInvestWelRatio;
       this.firstRegReward = firstRegReward;
       this.firstInvestRatio = firstInvestRatio;
       this.firstInvestReward = firstInvestReward;
       this.status = status;
       this.ctime = ctime;
       this.mtime = mtime;
       this.csysid = csysid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="plat_name")
    public Integer getPlatName() {
        return this.platName;
    }
    
    public void setPlatName(Integer platName) {
        this.platName = platName;
    }

    
    @Column(name="plat_code")
    public Integer getPlatCode() {
        return this.platCode;
    }
    
    public void setPlatCode(Integer platCode) {
        this.platCode = platCode;
    }

    
    @Column(name="point")
    public Integer getPoint() {
        return this.point;
    }
    
    public void setPoint(Integer point) {
        this.point = point;
    }

    
    @Column(name="point_val")
    public Integer getPointVal() {
        return this.pointVal;
    }
    
    public void setPointVal(Integer pointVal) {
        this.pointVal = pointVal;
    }

    
    @Column(name="wel_ticket_ratio")
    public Integer getWelTicketRatio() {
        return this.welTicketRatio;
    }
    
    public void setWelTicketRatio(Integer welTicketRatio) {
        this.welTicketRatio = welTicketRatio;
    }

    
    @Column(name="per_shake_cost")
    public Integer getPerShakeCost() {
        return this.perShakeCost;
    }
    
    public void setPerShakeCost(Integer perShakeCost) {
        this.perShakeCost = perShakeCost;
    }

    
    @Column(name="shake_rate")
    public Integer getShakeRate() {
        return this.shakeRate;
    }
    
    public void setShakeRate(Integer shakeRate) {
        this.shakeRate = shakeRate;
    }

    
    @Column(name="reg_send_money", precision=20, scale=0)
    public BigDecimal getRegSendMoney() {
        return this.regSendMoney;
    }
    
    public void setRegSendMoney(BigDecimal regSendMoney) {
        this.regSendMoney = regSendMoney;
    }

    
    @Column(name="first_invest_wel_ratio")
    public Integer getFirstInvestWelRatio() {
        return this.firstInvestWelRatio;
    }
    
    public void setFirstInvestWelRatio(Integer firstInvestWelRatio) {
        this.firstInvestWelRatio = firstInvestWelRatio;
    }

    
    @Column(name="first_reg_reward", precision=20, scale=0)
    public BigDecimal getFirstRegReward() {
        return this.firstRegReward;
    }
    
    public void setFirstRegReward(BigDecimal firstRegReward) {
        this.firstRegReward = firstRegReward;
    }

    
    @Column(name="first_invest_ratio")
    public Integer getFirstInvestRatio() {
        return this.firstInvestRatio;
    }
    
    public void setFirstInvestRatio(Integer firstInvestRatio) {
        this.firstInvestRatio = firstInvestRatio;
    }

    
    @Column(name="first_invest_reward", precision=20, scale=0)
    public BigDecimal getFirstInvestReward() {
        return this.firstInvestReward;
    }
    
    public void setFirstInvestReward(BigDecimal firstInvestReward) {
        this.firstInvestReward = firstInvestReward;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="csysid")
    public Integer getCsysid() {
        return this.csysid;
    }
    
    public void setCsysid(Integer csysid) {
        this.csysid = csysid;
    }




}


