package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxProvince generated by hbm2java
 */
@Entity
@Table(name="lx_province"
    ,catalog="lexiao"
)
public class LxProvince  implements java.io.Serializable {


     private String code;
     private String name;
     private char status;

    public LxProvince() {
    }

    public LxProvince(String code, String name, char status) {
       this.code = code;
       this.name = name;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=16)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


