package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxSearchHis generated by hbm2java
 */
@Entity
@Table(name="lx_search_his"
    ,catalog="lexiao"
)
public class LxSearchHis  implements java.io.Serializable {


     private Integer id;
     private String keys;
     private Integer nums;
     private Integer uid;
     private Integer ctime;
     private Integer mtime;

    public LxSearchHis() {
    }

    public LxSearchHis(String keys, Integer nums, Integer uid, Integer ctime, Integer mtime) {
       this.keys = keys;
       this.nums = nums;
       this.uid = uid;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="keys", length=100)
    public String getKeys() {
        return this.keys;
    }
    
    public void setKeys(String keys) {
        this.keys = keys;
    }

    
    @Column(name="nums")
    public Integer getNums() {
        return this.nums;
    }
    
    public void setNums(Integer nums) {
        this.nums = nums;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


