package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxSysOperLog generated by hbm2java
 */
@Entity
@Table(name="lx_sys_oper_log"
    ,catalog="lexiao"
)
public class LxSysOperLog  implements java.io.Serializable {


     private Integer id;
     private String data;
     private String operName;
     private Integer operId;
     private Byte operClient;
     private Byte operType;
     private Integer ctime;
     private String remark;

    public LxSysOperLog() {
    }

    public LxSysOperLog(String data, String operName, Integer operId, Byte operClient, Byte operType, Integer ctime, String remark) {
       this.data = data;
       this.operName = operName;
       this.operId = operId;
       this.operClient = operClient;
       this.operType = operType;
       this.ctime = ctime;
       this.remark = remark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="data", length=1000)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

    
    @Column(name="oper_name", length=50)
    public String getOperName() {
        return this.operName;
    }
    
    public void setOperName(String operName) {
        this.operName = operName;
    }

    
    @Column(name="oper_id")
    public Integer getOperId() {
        return this.operId;
    }
    
    public void setOperId(Integer operId) {
        this.operId = operId;
    }

    
    @Column(name="oper_client")
    public Byte getOperClient() {
        return this.operClient;
    }
    
    public void setOperClient(Byte operClient) {
        this.operClient = operClient;
    }

    
    @Column(name="oper_type")
    public Byte getOperType() {
        return this.operType;
    }
    
    public void setOperType(Byte operType) {
        this.operType = operType;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="remark", length=300)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


