package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxTag generated by hbm2java
 */
@Entity
@Table(name="lx_tag"
    ,catalog="lexiao"
)
public class LxTag  implements java.io.Serializable {


     private Integer id;
     private int PId;
     private String name;
     private Integer ctime;
     private Integer mtime;
     private Integer creator;
     private Integer modifier;

    public LxTag() {
    }

	
    public LxTag(int PId, String name) {
        this.PId = PId;
        this.name = name;
    }
    public LxTag(int PId, String name, Integer ctime, Integer mtime, Integer creator, Integer modifier) {
       this.PId = PId;
       this.name = name;
       this.ctime = ctime;
       this.mtime = mtime;
       this.creator = creator;
       this.modifier = modifier;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="p_id", nullable=false)
    public int getPId() {
        return this.PId;
    }
    
    public void setPId(int PId) {
        this.PId = PId;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="creator")
    public Integer getCreator() {
        return this.creator;
    }
    
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    
    @Column(name="modifier")
    public Integer getModifier() {
        return this.modifier;
    }
    
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }




}


