package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxUser generated by hbm2java
 */
@Entity
@Table(name="lx_user"
    ,catalog="lexiao"
)
public class LxUser  implements java.io.Serializable {


     private Integer uid;
     private String uscId;
     private String uname;
     private String mobile;
     private String personImg;
     private Boolean isSetUname;
     private String registerIp;
     private Integer lastLogintime;
     private Integer beforeLogintime;
     private Boolean isDel;
     private Integer mtime;
     private Integer ctime;
     private String source;
     private Boolean isApp;
     private Byte regSource;
     private Byte regClient;
     private Boolean isNewbie;
     private Byte uidType;
     private Integer investUsers;
     private String openid;
     private String accessToken;
     private String refreshToken;
     private String uscToken;
     private String deviceId;
     private Boolean isSetPwd;
     private String loginLat;
     private String loginLon;

    public LxUser() {
    }

    public LxUser(String uscId, String uname, String mobile, String personImg, Boolean isSetUname, String registerIp, Integer lastLogintime, Integer beforeLogintime, Boolean isDel, Integer mtime, Integer ctime, String source, Boolean isApp, Byte regSource, Byte regClient, Boolean isNewbie, Byte uidType, Integer investUsers, String openid, String accessToken, String refreshToken, String uscToken, String deviceId, Boolean isSetPwd, String loginLat, String loginLon) {
       this.uscId = uscId;
       this.uname = uname;
       this.mobile = mobile;
       this.personImg = personImg;
       this.isSetUname = isSetUname;
       this.registerIp = registerIp;
       this.lastLogintime = lastLogintime;
       this.beforeLogintime = beforeLogintime;
       this.isDel = isDel;
       this.mtime = mtime;
       this.ctime = ctime;
       this.source = source;
       this.isApp = isApp;
       this.regSource = regSource;
       this.regClient = regClient;
       this.isNewbie = isNewbie;
       this.uidType = uidType;
       this.investUsers = investUsers;
       this.openid = openid;
       this.accessToken = accessToken;
       this.refreshToken = refreshToken;
       this.uscToken = uscToken;
       this.deviceId = deviceId;
       this.isSetPwd = isSetPwd;
       this.loginLat = loginLat;
       this.loginLon = loginLon;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="uid", unique=true, nullable=false)
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="usc_id", length=18)
    public String getUscId() {
        return this.uscId;
    }
    
    public void setUscId(String uscId) {
        this.uscId = uscId;
    }

    
    @Column(name="uname", length=100)
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    
    @Column(name="mobile", length=30)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="person_img", length=200)
    public String getPersonImg() {
        return this.personImg;
    }
    
    public void setPersonImg(String personImg) {
        this.personImg = personImg;
    }

    
    @Column(name="is_set_uname")
    public Boolean getIsSetUname() {
        return this.isSetUname;
    }
    
    public void setIsSetUname(Boolean isSetUname) {
        this.isSetUname = isSetUname;
    }

    
    @Column(name="register_ip", length=80)
    public String getRegisterIp() {
        return this.registerIp;
    }
    
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    
    @Column(name="last_logintime")
    public Integer getLastLogintime() {
        return this.lastLogintime;
    }
    
    public void setLastLogintime(Integer lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    
    @Column(name="before_logintime")
    public Integer getBeforeLogintime() {
        return this.beforeLogintime;
    }
    
    public void setBeforeLogintime(Integer beforeLogintime) {
        this.beforeLogintime = beforeLogintime;
    }

    
    @Column(name="is_del")
    public Boolean getIsDel() {
        return this.isDel;
    }
    
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="source", length=50)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="is_app")
    public Boolean getIsApp() {
        return this.isApp;
    }
    
    public void setIsApp(Boolean isApp) {
        this.isApp = isApp;
    }

    
    @Column(name="reg_source")
    public Byte getRegSource() {
        return this.regSource;
    }
    
    public void setRegSource(Byte regSource) {
        this.regSource = regSource;
    }

    
    @Column(name="reg_client")
    public Byte getRegClient() {
        return this.regClient;
    }
    
    public void setRegClient(Byte regClient) {
        this.regClient = regClient;
    }

    
    @Column(name="is_newbie")
    public Boolean getIsNewbie() {
        return this.isNewbie;
    }
    
    public void setIsNewbie(Boolean isNewbie) {
        this.isNewbie = isNewbie;
    }

    
    @Column(name="uid_type")
    public Byte getUidType() {
        return this.uidType;
    }
    
    public void setUidType(Byte uidType) {
        this.uidType = uidType;
    }

    
    @Column(name="invest_users")
    public Integer getInvestUsers() {
        return this.investUsers;
    }
    
    public void setInvestUsers(Integer investUsers) {
        this.investUsers = investUsers;
    }

    
    @Column(name="openid", length=100)
    public String getOpenid() {
        return this.openid;
    }
    
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    
    @Column(name="access_token", length=200)
    public String getAccessToken() {
        return this.accessToken;
    }
    
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    
    @Column(name="refresh_token", length=200)
    public String getRefreshToken() {
        return this.refreshToken;
    }
    
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    
    @Column(name="usc_token", length=60)
    public String getUscToken() {
        return this.uscToken;
    }
    
    public void setUscToken(String uscToken) {
        this.uscToken = uscToken;
    }

    
    @Column(name="device_id", length=100)
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    
    @Column(name="is_set_pwd")
    public Boolean getIsSetPwd() {
        return this.isSetPwd;
    }
    
    public void setIsSetPwd(Boolean isSetPwd) {
        this.isSetPwd = isSetPwd;
    }

    
    @Column(name="login_lat", length=20)
    public String getLoginLat() {
        return this.loginLat;
    }
    
    public void setLoginLat(String loginLat) {
        this.loginLat = loginLat;
    }

    
    @Column(name="login_lon", length=20)
    public String getLoginLon() {
        return this.loginLon;
    }
    
    public void setLoginLon(String loginLon) {
        this.loginLon = loginLon;
    }




}


