package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxUserInvest generated by hbm2java
 */
@Entity
@Table(name="lx_user_invest"
    ,catalog="lexiao"
)
public class LxUserInvest  implements java.io.Serializable {


     private Integer id;
     private Integer uid;
     private Integer platId;
     private Integer mid;
     private Integer bid;
     private String prjNo;
     private String prjName;
     private String orderNo;
     private BigDecimal money;
     private Integer timeLimit;
     private String timeLimitUnit;
     private Byte isFirst;
     private Integer orderTime;
     private String repayWay;
     private Integer ctime;
     private Integer mtime;

    public LxUserInvest() {
    }

    public LxUserInvest(Integer uid, Integer platId, Integer mid, Integer bid, String prjNo, String prjName, String orderNo, BigDecimal money, Integer timeLimit, String timeLimitUnit, Byte isFirst, Integer orderTime, String repayWay, Integer ctime, Integer mtime) {
       this.uid = uid;
       this.platId = platId;
       this.mid = mid;
       this.bid = bid;
       this.prjNo = prjNo;
       this.prjName = prjName;
       this.orderNo = orderNo;
       this.money = money;
       this.timeLimit = timeLimit;
       this.timeLimitUnit = timeLimitUnit;
       this.isFirst = isFirst;
       this.orderTime = orderTime;
       this.repayWay = repayWay;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="plat_id")
    public Integer getPlatId() {
        return this.platId;
    }
    
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    
    @Column(name="mid")
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    
    @Column(name="bid")
    public Integer getBid() {
        return this.bid;
    }
    
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    
    @Column(name="prj_no", length=50)
    public String getPrjNo() {
        return this.prjNo;
    }
    
    public void setPrjNo(String prjNo) {
        this.prjNo = prjNo;
    }

    
    @Column(name="prj_name", length=200)
    public String getPrjName() {
        return this.prjName;
    }
    
    public void setPrjName(String prjName) {
        this.prjName = prjName;
    }

    
    @Column(name="order_no", length=50)
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="money", precision=20, scale=0)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    
    @Column(name="time_limit")
    public Integer getTimeLimit() {
        return this.timeLimit;
    }
    
    public void setTimeLimit(Integer timeLimit) {
        this.timeLimit = timeLimit;
    }

    
    @Column(name="time_limit_unit", length=20)
    public String getTimeLimitUnit() {
        return this.timeLimitUnit;
    }
    
    public void setTimeLimitUnit(String timeLimitUnit) {
        this.timeLimitUnit = timeLimitUnit;
    }

    
    @Column(name="is_first")
    public Byte getIsFirst() {
        return this.isFirst;
    }
    
    public void setIsFirst(Byte isFirst) {
        this.isFirst = isFirst;
    }

    
    @Column(name="order_time")
    public Integer getOrderTime() {
        return this.orderTime;
    }
    
    public void setOrderTime(Integer orderTime) {
        this.orderTime = orderTime;
    }

    
    @Column(name="repay_way", length=30)
    public String getRepayWay() {
        return this.repayWay;
    }
    
    public void setRepayWay(String repayWay) {
        this.repayWay = repayWay;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


