package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LxUserLoginLog generated by hbm2java
 */
@Entity
@Table(name="lx_user_login_log"
    ,catalog="lexiao"
)
public class LxUserLoginLog  implements java.io.Serializable {


     private LxUserLoginLogId id;

    public LxUserLoginLog() {
    }

    public LxUserLoginLog(LxUserLoginLogId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="uid", column=@Column(name="uid", nullable=false) ), 
        @AttributeOverride(name="sorcePlatfrom", column=@Column(name="sorce_platfrom", nullable=false, length=20) ), 
        @AttributeOverride(name="lat", column=@Column(name="lat", nullable=false) ), 
        @AttributeOverride(name="lon", column=@Column(name="lon", nullable=false) ), 
        @AttributeOverride(name="ctime", column=@Column(name="ctime", nullable=false) ), 
        @AttributeOverride(name="ip", column=@Column(name="ip", nullable=false) ) } )
    public LxUserLoginLogId getId() {
        return this.id;
    }
    
    public void setId(LxUserLoginLogId id) {
        this.id = id;
    }




}


