package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LxUserAccountRecord generated by hbm2java
 */
@Entity
@Table(name="lx_user_account_record"
    ,catalog="lexiao"
    , uniqueConstraints = @UniqueConstraint(columnNames="record_no") 
)
public class LxUserAccountRecord  implements java.io.Serializable {


     private Integer id;
     private Integer uid;
     private String recordNo;
     private Integer toUser;
     private Integer fromUser;
     private Byte inOrOut;
     private BigDecimal changeAmount;
     private BigDecimal fromAmount;
     private BigDecimal toAmount;
     private BigDecimal fromCashFreezeMoney;
     private BigDecimal toCashFreezeMoney;
     private BigDecimal fromPayFreezeMoney;
     private BigDecimal toPayFreezeMoney;
     private String remark;
     private Integer ticketId;
     private Integer cashId;
     private Integer userOrderId;
     private Integer ctime;
     private Integer mtime;

    public LxUserAccountRecord() {
    }

    public LxUserAccountRecord(Integer uid, String recordNo, Integer toUser, Integer fromUser, Byte inOrOut, BigDecimal changeAmount, BigDecimal fromAmount, BigDecimal toAmount, BigDecimal fromCashFreezeMoney, BigDecimal toCashFreezeMoney, BigDecimal fromPayFreezeMoney, BigDecimal toPayFreezeMoney, String remark, Integer ticketId, Integer cashId, Integer userOrderId, Integer ctime, Integer mtime) {
       this.uid = uid;
       this.recordNo = recordNo;
       this.toUser = toUser;
       this.fromUser = fromUser;
       this.inOrOut = inOrOut;
       this.changeAmount = changeAmount;
       this.fromAmount = fromAmount;
       this.toAmount = toAmount;
       this.fromCashFreezeMoney = fromCashFreezeMoney;
       this.toCashFreezeMoney = toCashFreezeMoney;
       this.fromPayFreezeMoney = fromPayFreezeMoney;
       this.toPayFreezeMoney = toPayFreezeMoney;
       this.remark = remark;
       this.ticketId = ticketId;
       this.cashId = cashId;
       this.userOrderId = userOrderId;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="record_no", unique=true, length=50)
    public String getRecordNo() {
        return this.recordNo;
    }
    
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    
    @Column(name="to_user")
    public Integer getToUser() {
        return this.toUser;
    }
    
    public void setToUser(Integer toUser) {
        this.toUser = toUser;
    }

    
    @Column(name="from_user")
    public Integer getFromUser() {
        return this.fromUser;
    }
    
    public void setFromUser(Integer fromUser) {
        this.fromUser = fromUser;
    }

    
    @Column(name="in_or_out")
    public Byte getInOrOut() {
        return this.inOrOut;
    }
    
    public void setInOrOut(Byte inOrOut) {
        this.inOrOut = inOrOut;
    }

    
    @Column(name="change_amount", precision=20, scale=0)
    public BigDecimal getChangeAmount() {
        return this.changeAmount;
    }
    
    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    
    @Column(name="from_amount", precision=20, scale=0)
    public BigDecimal getFromAmount() {
        return this.fromAmount;
    }
    
    public void setFromAmount(BigDecimal fromAmount) {
        this.fromAmount = fromAmount;
    }

    
    @Column(name="to_amount", precision=20, scale=0)
    public BigDecimal getToAmount() {
        return this.toAmount;
    }
    
    public void setToAmount(BigDecimal toAmount) {
        this.toAmount = toAmount;
    }

    
    @Column(name="from_cash_freeze_money", precision=20, scale=0)
    public BigDecimal getFromCashFreezeMoney() {
        return this.fromCashFreezeMoney;
    }
    
    public void setFromCashFreezeMoney(BigDecimal fromCashFreezeMoney) {
        this.fromCashFreezeMoney = fromCashFreezeMoney;
    }

    
    @Column(name="to_cash_freeze_money", precision=20, scale=0)
    public BigDecimal getToCashFreezeMoney() {
        return this.toCashFreezeMoney;
    }
    
    public void setToCashFreezeMoney(BigDecimal toCashFreezeMoney) {
        this.toCashFreezeMoney = toCashFreezeMoney;
    }

    
    @Column(name="from_pay_freeze_money", precision=20, scale=0)
    public BigDecimal getFromPayFreezeMoney() {
        return this.fromPayFreezeMoney;
    }
    
    public void setFromPayFreezeMoney(BigDecimal fromPayFreezeMoney) {
        this.fromPayFreezeMoney = fromPayFreezeMoney;
    }

    
    @Column(name="to_pay_freeze_money", precision=20, scale=0)
    public BigDecimal getToPayFreezeMoney() {
        return this.toPayFreezeMoney;
    }
    
    public void setToPayFreezeMoney(BigDecimal toPayFreezeMoney) {
        this.toPayFreezeMoney = toPayFreezeMoney;
    }

    
    @Column(name="remark", length=1000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="ticket_id")
    public Integer getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    
    @Column(name="cash_id")
    public Integer getCashId() {
        return this.cashId;
    }
    
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }

    
    @Column(name="user_order_id")
    public Integer getUserOrderId() {
        return this.userOrderId;
    }
    
    public void setUserOrderId(Integer userOrderId) {
        this.userOrderId = userOrderId;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


