package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * LxUserAccount generated by hbm2java
 */
@Entity
@Table(name="lx_user_account"
    ,catalog="lexiao"
)
public class LxUserAccount  implements java.io.Serializable {


     private Integer id;
     private Integer version;
     private Integer uid;
     private String payPassword;
     private String payPasswordMobile;
     private BigDecimal amount;
     private BigDecimal cashFreezeMoney;
     private BigDecimal payFreezeMoney;
     private Integer ctime;
     private Integer mtime;

    public LxUserAccount() {
    }

    public LxUserAccount(Integer uid, String payPassword, String payPasswordMobile, BigDecimal amount, BigDecimal cashFreezeMoney, BigDecimal payFreezeMoney, Integer ctime, Integer mtime) {
       this.uid = uid;
       this.payPassword = payPassword;
       this.payPasswordMobile = payPasswordMobile;
       this.amount = amount;
       this.cashFreezeMoney = cashFreezeMoney;
       this.payFreezeMoney = payFreezeMoney;
       this.ctime = ctime;
       this.mtime = mtime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    
    @Column(name="uid")
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    
    @Column(name="pay_password", length=60)
    public String getPayPassword() {
        return this.payPassword;
    }
    
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }

    
    @Column(name="pay_password_mobile", length=60)
    public String getPayPasswordMobile() {
        return this.payPasswordMobile;
    }
    
    public void setPayPasswordMobile(String payPasswordMobile) {
        this.payPasswordMobile = payPasswordMobile;
    }

    
    @Column(name="amount", precision=20, scale=0)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="cash_freeze_money", precision=20, scale=0)
    public BigDecimal getCashFreezeMoney() {
        return this.cashFreezeMoney;
    }
    
    public void setCashFreezeMoney(BigDecimal cashFreezeMoney) {
        this.cashFreezeMoney = cashFreezeMoney;
    }

    
    @Column(name="pay_freeze_money", precision=20, scale=0)
    public BigDecimal getPayFreezeMoney() {
        return this.payFreezeMoney;
    }
    
    public void setPayFreezeMoney(BigDecimal payFreezeMoney) {
        this.payFreezeMoney = payFreezeMoney;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }




}


