package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxWelfare generated by hbm2java
 */
@Entity
@Table(name="lx_welfare"
    ,catalog="lexiao"
)
public class LxWelfare  implements java.io.Serializable {


     private Integer id;
     private Integer coopPlat;
     private Byte type;
     private Integer belong;
     private String ticketType;
     private BigDecimal ticketPrice;
     private Integer sellNum;
     private Integer takedNum;
     private String useTip;
     private Integer sortNo;
     private Byte isActive;
     private Integer ctime;
     private Integer mtime;
     private Integer csysid;

    public LxWelfare() {
    }

    public LxWelfare(Integer coopPlat, Byte type, Integer belong, String ticketType, BigDecimal ticketPrice, Integer sellNum, Integer takedNum, String useTip, Integer sortNo, Byte isActive, Integer ctime, Integer mtime, Integer csysid) {
       this.coopPlat = coopPlat;
       this.type = type;
       this.belong = belong;
       this.ticketType = ticketType;
       this.ticketPrice = ticketPrice;
       this.sellNum = sellNum;
       this.takedNum = takedNum;
       this.useTip = useTip;
       this.sortNo = sortNo;
       this.isActive = isActive;
       this.ctime = ctime;
       this.mtime = mtime;
       this.csysid = csysid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="coop_plat")
    public Integer getCoopPlat() {
        return this.coopPlat;
    }
    
    public void setCoopPlat(Integer coopPlat) {
        this.coopPlat = coopPlat;
    }

    
    @Column(name="type")
    public Byte getType() {
        return this.type;
    }
    
    public void setType(Byte type) {
        this.type = type;
    }

    
    @Column(name="belong")
    public Integer getBelong() {
        return this.belong;
    }
    
    public void setBelong(Integer belong) {
        this.belong = belong;
    }

    
    @Column(name="ticket_type", length=50)
    public String getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }

    
    @Column(name="ticket_price", precision=20, scale=0)
    public BigDecimal getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(BigDecimal ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    
    @Column(name="sell_num")
    public Integer getSellNum() {
        return this.sellNum;
    }
    
    public void setSellNum(Integer sellNum) {
        this.sellNum = sellNum;
    }

    
    @Column(name="taked_num")
    public Integer getTakedNum() {
        return this.takedNum;
    }
    
    public void setTakedNum(Integer takedNum) {
        this.takedNum = takedNum;
    }

    
    @Column(name="use_tip", length=100)
    public String getUseTip() {
        return this.useTip;
    }
    
    public void setUseTip(String useTip) {
        this.useTip = useTip;
    }

    
    @Column(name="sort_no")
    public Integer getSortNo() {
        return this.sortNo;
    }
    
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    
    @Column(name="is_active")
    public Byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="csysid")
    public Integer getCsysid() {
        return this.csysid;
    }
    
    public void setCsysid(Integer csysid) {
        this.csysid = csysid;
    }




}


