package com.cs.lexiao.admin.mapping.business;
// Generated Dec 14, 2017 6:24:57 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LxWelfareConfig generated by hbm2java
 */
@Entity
@Table(name="lx_welfare_config"
    ,catalog="lexiao"
)
public class LxWelfareConfig  implements java.io.Serializable {


     private Integer id;
     private Integer coopPlat;
     private Integer ruleName;
     private Integer conType;
     private String dayFreeTimes;
     private BigDecimal winRate;
     private Integer extraGetName;
     private Integer extraGetValue;
     private Integer ctime;
     private Integer mtime;
     private Integer csysid;

    public LxWelfareConfig() {
    }

    public LxWelfareConfig(Integer coopPlat, Integer ruleName, Integer conType, String dayFreeTimes, BigDecimal winRate, Integer extraGetName, Integer extraGetValue, Integer ctime, Integer mtime, Integer csysid) {
       this.coopPlat = coopPlat;
       this.ruleName = ruleName;
       this.conType = conType;
       this.dayFreeTimes = dayFreeTimes;
       this.winRate = winRate;
       this.extraGetName = extraGetName;
       this.extraGetValue = extraGetValue;
       this.ctime = ctime;
       this.mtime = mtime;
       this.csysid = csysid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="coop_plat")
    public Integer getCoopPlat() {
        return this.coopPlat;
    }
    
    public void setCoopPlat(Integer coopPlat) {
        this.coopPlat = coopPlat;
    }

    
    @Column(name="rule_name")
    public Integer getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(Integer ruleName) {
        this.ruleName = ruleName;
    }

    
    @Column(name="con_type")
    public Integer getConType() {
        return this.conType;
    }
    
    public void setConType(Integer conType) {
        this.conType = conType;
    }

    
    @Column(name="day_free_times", length=50)
    public String getDayFreeTimes() {
        return this.dayFreeTimes;
    }
    
    public void setDayFreeTimes(String dayFreeTimes) {
        this.dayFreeTimes = dayFreeTimes;
    }

    
    @Column(name="win_rate", precision=20, scale=0)
    public BigDecimal getWinRate() {
        return this.winRate;
    }
    
    public void setWinRate(BigDecimal winRate) {
        this.winRate = winRate;
    }

    
    @Column(name="extra_get_name")
    public Integer getExtraGetName() {
        return this.extraGetName;
    }
    
    public void setExtraGetName(Integer extraGetName) {
        this.extraGetName = extraGetName;
    }

    
    @Column(name="extra_get_value")
    public Integer getExtraGetValue() {
        return this.extraGetValue;
    }
    
    public void setExtraGetValue(Integer extraGetValue) {
        this.extraGetValue = extraGetValue;
    }

    
    @Column(name="ctime")
    public Integer getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    
    @Column(name="mtime")
    public Integer getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }

    
    @Column(name="csysid")
    public Integer getCsysid() {
        return this.csysid;
    }
    
    public void setCsysid(Integer csysid) {
        this.csysid = csysid;
    }




}


