package com.cs.lexiao.admin.mapping.basesystem.dictionary;

/**
 * FieldCodeMap generated by MyEclipse Persistence Tools
 * 
 * @author shentuwy
 */

public class FieldCodeMap implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 3354146861474054760L;

	/** ID */
	private Long				id;

	public static final String	ID					= "id";

	/** 表名 */
	private String				tableName;

	public static final String	TABLE_NAME			= "tableName";

	/** 字段名 */
	private String				fieldName;

	public static final String	FIELD_NAME			= "fieldName";

	/** 代码 */
	private String				codeKey;

	public static final String	CODE_KEY			= "codeKey";

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getCodeKey() {
		return codeKey;
	}

	public void setCodeKey(String codeKey) {
		this.codeKey = codeKey;
	}

}
